//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataRepository.DataSource
{
    using System;
    using System.Collections.Generic;
    
    public partial class MailConfiguration
    {
        public int Id { get; set; }
        public string UserId { get; set; }
        public string ImapEmailId { get; set; }
        public string ImapEmailPassword { get; set; }
        public string SMTPEmailId { get; set; }
        public string SMTPEmailPassword { get; set; }
        public System.DateTime CreatedDate { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
    }
}
